In [1]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

print(m[1, 0])

print(m[1, :])

print(m[:, 2])

print(m[1, 2:])

print(m[0:2, 1])

print(m[0:2, 1:3])

cols = [0, 1, 3]
m[:, cols]

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
5
[[5 6 7 8]]
[[3]
 [7]
 [5]]
[[7 8]]
[[2]
 [6]]
[[2 3]
 [6 7]]


matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [2]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
type(m)

n = np.array(m)
type(n)

m.shape

m.max()
np.max(m)

m.max(axis=1)

m.max(axis=0)

m.mean()
m.sum(axis=0)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


matrix([[15,  9, 15, 19]])

In [3]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

less_then_5 = nums < 5
print(less_then_5)

pos_a = letters == 'a'
pos_a

nums[less_then_5]


[ True  True  True  True False False False False False False]


array([1, 2, 3, 4])

In [4]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
mod_m = np.logical_and(m>=3, m<=7)
print(mod_m)

m[mod_m]


[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
[[False False  True  True]
 [ True  True  True False]
 [False False  True  True]]


matrix([[3, 4, 5, 6, 7, 5, 7]])

In [5]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums[nums < 5]


array([1, 2, 3, 4])

In [6]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [7]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]
