<font size=4> <b> Задание: </b> Дана целочисленная квадратная матрица. Определить:
сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы. </h3>
</font>

In [1]:
import numpy as np
import random
n = 5
random.seed(10)
arr = np.random.randint(-3, 30, size=(n, n))

print(arr)
summ = arr[:, (arr>=0).all(axis=0)].sum()
minn = min([np.fliplr(arr).diagonal(i).sum() for i in range(-(n-1), n)])

print("Сумма элементов в столбцах, не содержащих отрицательных элементов:", summ)
print("Минимум среди сумм модулей элементов диагоналей, параллельных побочной: ",minn)

[[18  6 -3  0 -3]
 [ 8 11 13 -3  8]
 [12  4  8 25  8]
 [ 1 24 21  4 10]
 [-1  1  8 17  5]]
Сумма элементов в столбцах, не содержащих отрицательных элементов: 46
Минимум среди сумм модулей элементов диагоналей, параллельных побочной:  5
