<font size=4> <b> Задание: </b> Дана целочисленная квадратная матрица. Определить:
сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы. </h3>
</font>

In [1]:
import numpy as np
import random
n = 10
random.seed(10)
arr = np.random.randint(-3, 30, size=(n, n))

print(arr)
summ = arr[:, (arr>=0).all(axis=0)].sum()
minn = min([np.fliplr(arr).diagonal(i).sum() for i in range(-(n-1), n)])

print("Сумма элементов в столбцах, не содержащих отрицательных элементов:", summ)
print("Минимум среди сумм модулей элементов диагоналей, параллельных побочной: ",minn)

[[16 11 20  7 19  1 23 22  2 10]
 [ 1 22  2  2 19 10 18  8 18  3]
 [20  4  1  3  2 24 15 -2 19 -3]
 [20  8 24 23 27 11  2 29 24 29]
 [22 12 24  0 25 16 17 17 22 16]
 [14 -2 11 11 26 22 19 22  5 26]
 [26 16 19  8  5 20 13  4 29  1]
 [10 20  8  0  9 10  6 13 15 25]
 [17 18 20 28 18 22 28  9 14  0]
 [ 8 14 28  1  5 19 20 17 12 16]]
Сумма элементов в столбцах, не содержащих отрицательных элементов: 1025
Минимум среди сумм модулей элементов диагоналей, параллельных побочной:  12
