

# Лабораторная работа 3.2. Знакомство с NumPy
Библиотека NumPy -- быстрая библиотека для математики в Python, основная структура данных -- массив `numpy.array`:

![](https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif)

In [1]:
# подключение модуля numpy под именем np
import numpy as np

In [2]:
# основная структура данных - массив
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print("a =", a)
print("b =", b)

a = [1 2 3 4 5]
b = [0.1 0.2 0.3 0.4 0.5]


Создайте массив с 5 любыми числами:

In [3]:
m = np.matrix('20 74 43 97 35')
print(m)

[[20 74 43 97 35]]


Арифметические операции, в отличие от операций над списками, применяются поэлементно:

In [4]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

print("list1:", list1)
print('\tlist1 * 3:', list1 * 3)
print('\tlist1 + [1]:', list1 + [1])

print('array1:', array1)
print('\tarray1 * 3:', array1 * 3)
print('\tarray1 + 1:', array1 + 1)

list1: [1, 2, 3]
	list1 * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
	list1 + [1]: [1, 2, 3, 1]
array1: [1 2 3]
	array1 * 3: [3 6 9]
	array1 + 1: [2 3 4]


Создайте массив из 5 чисел. Возведите каждый элемент массива в степень 3

In [5]:
m = np.matrix('20 74 43 97 35')
m_array = np.array(m)
print(m_array ** 3)

[[  8000 405224  79507 912673  42875]]


Если в операции участвуют $2$ массива (по умолчанию -- одинакового размера), операции считаются для соответствующих пар:

In [6]:
print("a + b =", a + b)
print("a * b =", a * b)

a + b = [1.1 2.2 3.3 4.4 5.5]
a * b = [0.1 0.4 0.9 1.6 2.5]


In [7]:
# вот это разность
print("a - b =", a - b)

# вот это деление
print("a / b =", a / b)

# вот это целочисленное деление
print("a // b =", a // b)

# вот это квадрат
print("a ** 2 =", a ** 2)

a - b = [0.9 1.8 2.7 3.6 4.5]
a / b = [10. 10. 10. 10. 10.]
a // b = [ 9.  9. 10.  9. 10.]
a ** 2 = [ 1  4  9 16 25]


 Создайте два массива одинаковой длины. Выведите массив, полученный делением одного массива на другой.

In [8]:
m1 = np.matrix('24 12 54 76 44 88')
m2 = np.matrix('76 44 42 54 12 6')

print(m1 / m2)


[[ 0.31578947  0.27272727  1.28571429  1.40740741  3.66666667 14.66666667]]


#### *Л — логика*
К элементам массива можно применять логические операции.

Возвращаемое значение -- массив, содержащий результаты вычислений для каждого элемента (`True` -- "да" или `False` -- "нет"):

In [9]:
print("a =", a)
print("\ta > 1: ", a > 1)
print("\nb =", b)
print("\tb < 0.5:  ", b < 0.5)

print("\nОдновременная проверка условий:")
print("\t(a > 1) & (b < 0.5):  ", (a>1) & (b < 0.5))
print("А вот это проверяет, что a > 1 ИЛИ b < 0.5:  ", (a > 1) | (b < 0.5))

a = [1 2 3 4 5]
	a > 1:  [False  True  True  True  True]

b = [0.1 0.2 0.3 0.4 0.5]
	b < 0.5:   [ True  True  True  True False]

Одновременная проверка условий:
	(a > 1) & (b < 0.5):   [False  True  True  True False]
А вот это проверяет, что a > 1 ИЛИ b < 0.5:   [ True  True  True  True  True]


Создайте 2 массива из 5 элементов. Проверьте условие "Элементы первого массива меньше 6, элементы второго массива делятся на 3"

In [10]:
n1 = np.matrix('1 3 2 97 5')
n2 = np.matrix('90 56 23 66 33')

print((n1 < 6) & (n2%3==0))

[[ True False False False  True]]


Теперь проверьте условие "Элементы первого массива делятся на 2 или элементы второго массива больше 2"

In [11]:
n1 = np.matrix('1 3 2 97 5')
n2 = np.matrix('90 56 23 66 33')

print((n1 % 2 == 0) | (n2 > 2))

n1 = np.matrix('2 4 6 8 10')
n2 = np.matrix('2 2 2 2 2')

print((n1 % 2 == 0) | (n2 > 2))

[[ True  True  True  True  True]]
[[ True  True  True  True  True]]


Зачем это нужно? Чтобы выбирать элементы массива, удовлетворяющие какому-нибудь условию:

In [12]:
print("a =", a)
print("a > 2:", a > 2)
# индексация - выбираем элементы из массива в тех позициях, где True
print("a[a > 2]:", a[a > 2])

a = [1 2 3 4 5]
a > 2: [False False  True  True  True]
a[a > 2]: [3 4 5]


Создайте массив с элементами от 1 до 20. Выведите все элементы, которые больше 5 и не делятся на 2

Подсказка: создать массив можно с помощью функции np.arange(), действие которой аналогично функции range, которую вы уже знаете.

In [13]:
num_arr = np.arange(1, 60, 3)
print(num_arr)
type(num_arr)
# print(num_arr[num_arr > 5])
condition = (num_arr > 5) & (num_arr % 2 !=0)
num_arr[condition]


[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58]


array([ 7, 13, 19, 25, 31, 37, 43, 49, 55])

#### А ещё NumPy умеет...

Все операции NumPy оптимизированы для быстрых вычислений над целыми массивами чисел и в методах `np.array` реализовано множество функций, которые могут вам понадобиться:

In [14]:
# теперь можно считать средний размер котиков в одну строку!
print("np.mean(a) =", np.mean(a))
# минимальный элемент
print("np.min(a) =", np.min(a))
# индекс минимального элемента
print("np.argmin(a) =", np.argmin(a))
# вывести значения массива без дубликатов
print("np.unique(['male', 'male', 'female', 'female', 'male']) =", np.unique(['male', 'male', 'female', 'female', 'male']))

# и ещё много всяких методов
# Google в помощь

np.mean(a) = 3.0
np.min(a) = 1
np.argmin(a) = 0
np.unique(['male', 'male', 'female', 'female', 'male']) = ['female' 'male']


---

---

Пора еще немного потренироваться с NumPy.

Выполните операции, перечисленные ниже:

In [15]:
print(a)
print(b)

print("Разность между a и b:", a - b
     )
print("Квадраты элементов b:", b ** 2
     )
print("Половины произведений элементов массивов a и b:", (a * b) / 2
     )

print()
print("Максимальный элемент b:", max(b)
     )
print("Сумма элементов массива b:", sum(b)
     )
print("Индекс максимального элемента b:", b.argmax()
     )

[1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]
Разность между a и b: [0.9 1.8 2.7 3.6 4.5]
Квадраты элементов b: [0.01 0.04 0.09 0.16 0.25]
Половины произведений элементов массивов a и b: [0.05 0.2  0.45 0.8  1.25]

Максимальный элемент b: 0.5
Сумма элементов массива b: 1.5
Индекс максимального элемента b: 4


 Задайте два массива: [5, 2, 3, 12, 4, 5]   и   ['f', 'o', 'o', 'b', 'a', 'r']

Выведите буквы из второго массива, индексы которых соответствуют индексам чисел из первого массива, которые больше 1, меньше 5 и делятся на 2

In [16]:
arr = np.array([5, 2, 3, 12, 4, 5])
letters = np.array(['f', 'o', 'o', 'b', 'a', 'r'])
print(letters[np.logical_and(arr > 1, arr < 5, arr % 2 == 0)])

['o' 'o' 'a']
